import { StyleSheet } from 'react-native';
import {
  heightPercentageToDP,
  PixelRatio,
  PixelToDP, responsiveFontSize,
  widthPercentageToDP,
} from './PixelRatio';
// import { BtnTxtColor, viewColor, labelColor } from "./CustomColor";

export const styles = StyleSheet.create({
  flexScreen: {
    flex: 1,
    width: widthPercentageToDP(100)
  },
  titlebar: {
    height: responsiveFontSize(9),
    width: widthPercentageToDP(100),
    backgroundColor: '#22DCD3',
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomColor: 'white',
    borderBottomWidth: 4,
    paddingBottom: 5,
    paddingTop: 5,
    marginBottom: 0,
    //paddingTop: Platform.OS === 'android' ? PixelToDP(30) : 0
  },
  titlebarHome: {
    height: responsiveFontSize(9),
    width: widthPercentageToDP(100),
    backgroundColor: '#22DCD3',
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomColor: 'white',
    borderBottomWidth: 4,
    paddingBottom: 25,
    paddingTop: 5,
    marginBottom: 6,
    paddingTop: Platform.OS === 'android' ? PixelToDP(30) : 0
  },
  boxShadow: {
    shadowColor: '#121010',
    shadowOffset: {
      width: 0,
      height: 6,
    },
    shadowOpacity: 0.8,
    shadowRadius: 3.84,
    elevation: 6,
  },
  homeButton: {
    borderWidth: PixelToDP(2.5),
    alignSelf: 'center',
    borderColor: '#58c3be',
    width: 'auto',
    height: 'auto',
    margin: PixelToDP(12),
    padding: PixelToDP(10),
    borderRadius: PixelToDP(50),
    backgroundColor: 'white',
    shadowColor: '#121010',
    shadowOffset: {
      width: 0,
      height: 6,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 6,
  },
  homeButtonText: {
    color: '#358e89',
    fontSize: responsiveFontSize(2.2),
    textTransform: 'capitalize',
    fontFamily: 'SourceSansPro-Regular',
    letterSpacing: 0.7,
  },
  homeRoundButtons: {
    width: widthPercentageToDP(35),
    height: widthPercentageToDP(35),
    borderRadius: widthPercentageToDP(35),
    backgroundColor: '#30B3AB',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column',
    //borderColor:"#31847f",
    borderColor: "#3a9f9a",
    borderWidth: 4,
    shadowColor: '#121010',
    shadowOffset: {
      width: 0,
      height: 6,
    },
    shadowOpacity: 0.4,
    shadowRadius: 3.84,
    elevation: 6,
  },
  homeText: {
    fontSize: responsiveFontSize(2.5),
    color: 'white',
    width: '100%',
    height: 'auto',
    textAlign: 'center',
    lineHeight: PixelToDP(25),
    fontFamily: 'SourceSansPro-Regular',
    letterSpacing: 0.6,
    margin: 'auto',
  },
  titleRightButton: {
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center'
  },
  backLogo: {
    color: 'white',
    fontFamily: "SourceSansPro-Regular",
    fontSize: responsiveFontSize(2),
    marginLeft: PixelToDP(3),
    width: widthPercentageToDP(30),
  },
  backImageIcon: {
    width: PixelToDP(8),
    height: PixelToDP(15),
    alignSelf: 'center'
  },
  backTouch: {
    flexDirection: 'row',
    width: '27%',
    marginLeft: widthPercentageToDP(3)
  },
  titleText: {
    fontSize: responsiveFontSize(2.6),
    fontFamily: "SourceSansPro-Regular",
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
    width: '40%',
    alignSelf: 'center',
  },
  aboutBack: {
    textTransform: 'uppercase',
    fontSize: responsiveFontSize(2),
    color: 'white',
    textAlign: 'center',
    textAlignVertical: 'center',
    marginLeft: PixelToDP(2)
  },
  titleRightView: {
    width: widthPercentageToDP(20),
    height: PixelToDP(30),
    position: 'absolute',
    right: PixelToDP(10),
  },
  settingHeading: {
    color: 'white',
    fontSize: responsiveFontSize(2.4),
    fontFamily: "SourceSansPro-Regular",
    fontWeight: 'bold',
    lineHeight: PixelToDP(25),
    textTransform: 'uppercase',
  },
  settingText: {
    color: 'white',
    fontSize: responsiveFontSize(2.6),
    lineHeight: PixelToDP(30),
    textAlignVertical: 'center',
    textTransform: "capitalize",
    borderBottomColor: '#fff',
    borderBottomWidth: 1,
    paddingBottom: 10,
    marginTop: 10
  },
  settingText2: {
    fontSize: responsiveFontSize(2.5),
    fontWeight: 'bold',
    // height: PixelToDP(60),
    width: '70%',
    marginBottom: PixelToDP(20),
    textAlign: 'center',
    textAlignVertical: 'center',
    color: "#3a9f9a",
    alignSelf: "center"
  },

  OswaldFont: {
    fontFamily: "SourceSansPro-Regular",
  },
  calendar: {
    borderTopWidth: 1,
    paddingTop: 5,
    borderBottomWidth: 1,
    borderColor: '#eee',
    width: widthPercentageToDP(90),
    height: '100%',
    alignSelf: 'center',
    borderRadius: PixelToDP(30),
  },
  taskImageGreen: {
    tintColor: '#30B3AB',
  },
  taskImageBorderWhite: {
    height: PixelToDP(45),
    width: PixelToDP(45),
    marginTop: PixelToDP(10),
    borderRadius: PixelToDP(35),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'white',
  },
  taskImageWhite: {
    tintColor: 'white',
  },
  goalIconBorder: {
    height: PixelToDP(55),
    width: PixelToDP(55),
    marginTop: PixelToDP(10),
    borderRadius: PixelToDP(55),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'white',
    borderColor: 'black',
    borderWidth: PixelToDP(1),
  },

  taskImageBorderGreen: {
    height: responsiveFontSize(5.2),
    width: responsiveFontSize(5.2),
    marginTop: PixelToDP(5),
    marginBottom: PixelToDP(5),
    borderRadius: PixelToDP(35),
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: PixelToDP(1),
    borderColor: '#30B3AB',
  },
  taskImageBorderToDoWhite: {
    height: responsiveFontSize(5),
    width: responsiveFontSize(5),
    marginTop: PixelToDP(5),
    marginBottom: PixelToDP(5),
    borderRadius: PixelToDP(35),
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: PixelToDP(1),
    borderColor: '#ffffff',
  },
  addTaskTextInput: {
    width: '90%',
    alignSelf: 'center',
    height: PixelToDP(41),
    borderRadius: PixelToDP(20),
    marginBottom: PixelToDP(20),
    borderColor: '#C4C4C4',
    borderWidth: PixelToDP(1),
    textAlign: 'center',
    padding: PixelToDP(10),
    fontFamily: "SourceSansPro-Regular",
    fontSize: responsiveFontSize(1.5)
  },
  addTaskDescTextInput: {
    width: '90%',
    alignSelf: 'center',
    height: PixelToDP(130),
    borderRadius: PixelToDP(16),
    marginBottom: PixelToDP(20),
    borderColor: '#C4C4C4',
    borderWidth: PixelToDP(1),
    padding: PixelToDP(10),
    fontSize: PixelToDP(12),
    fontFamily: "SourceSansPro-Regular",
    textAlign: 'left',
  },
  addTaskDescTextInputGoal: {
    width: '98%',
    borderRadius: PixelToDP(0),
    marginBottom: PixelToDP(20),
    marginTop: PixelToDP(20),
    padding: PixelToDP(10),
    fontSize: PixelToDP(18),
    fontFamily: "SourceSansPro-Regular",
    textAlign: 'left',
    color: "white",
    alignSelf: "flex-start",
    justifyContent: "flex-start",
    textAlignVertical: 'top',
    borderTopWidth: 2,
    borderBottomWidth: 2,
    height: heightPercentageToDP(25),
    borderColor: "#fff"
  },
  addTaskDescTextInputGoalTask: {
    width: '98%',
    borderRadius: PixelToDP(0),
    marginBottom: PixelToDP(10),
    marginTop: PixelToDP(10),
    padding: PixelToDP(10),
    fontSize: PixelToDP(12),
    fontFamily: "SourceSansPro-Regular",
    textAlign: 'left',
    color: "white",
    alignSelf: "flex-start",
    justifyContent: "flex-start",
    textAlignVertical: 'top',
    borderTopWidth: 2,
    borderBottomWidth: 2,
    height: heightPercentageToDP(20),
    borderColor: "#fff"
  },
  taskStatusView: {
    backgroundColor: "#4bc9c1",
    width: widthPercentageToDP(26),
    borderRadius: PixelToDP(10),
    borderColor: '#30B3AB',
    alignItems: 'center',
    justifyContent: "space-between",
    padding: PixelToDP(5),
    marginLeft: 6,
    paddingTop: 10,
    paddingBottom: 10,
    shadowColor: '#121010',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.8,
    shadowRadius: 3.84,
    elevation: 3,
    borderWidth: PixelToDP(2),

  },
  taskStatusText: {
    alignSelf: 'center',
    fontSize: PixelToDP(16),
    textAlign: 'center',
    fontFamily: "SourceSansPro-Regular",
    color: "#fff",
    fontSize: responsiveFontSize(2.4)

  },

  taskStatusViewActive: {
    width: widthPercentageToDP(26),
    borderRadius: PixelToDP(10),
    borderColor: '#30B3AB',
    borderWidth: PixelToDP(2),
    alignItems: 'center',
    justifyContent: "space-between",
    padding: PixelToDP(5),
    marginLeft: 6,
    paddingTop: 10,
    paddingBottom: 10,
    shadowColor: '#121010',
    backgroundColor: "#35928d",
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.8,
    shadowRadius: 3.84,
    elevation: 3,

  },
  taskStatusViewActive2: {
    width: widthPercentageToDP(26),
    borderRadius: PixelToDP(10),
    borderColor: '#30B3AB',
    borderWidth: PixelToDP(2),
    alignItems: 'center',
    justifyContent: "space-between",
    padding: PixelToDP(5),
    marginLeft: 6,
    paddingTop: 10,
    paddingBottom: 10,
    shadowColor: '#121010',
    backgroundColor: "#35928d",
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowOpacity: 0.8,
    shadowRadius: 3.84,
    elevation: 5,
    height: 70,
    paddingBottom: 15
  },
  taskStatusView2: {
    paddingBottom: 15,
    backgroundColor: "#4bc9c1",
    width: widthPercentageToDP(26),
    borderRadius: PixelToDP(10),
    borderColor: '#30B3AB',
    alignItems: 'center',
    justifyContent: "space-between",
    padding: PixelToDP(5),
    marginLeft: 6,
    paddingTop: 10,
    paddingBottom: 10,
    shadowColor: '#121010',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.8,
    shadowRadius: 3.84,
    elevation: 3,
    borderWidth: PixelToDP(2),
    height: 70,
  },

  AddIcon: {
    height: PixelToDP(53),
    width: PixelToDP(53),
    marginTop: PixelToDP(9),
    borderRadius: PixelToDP(50),
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: PixelToDP(3),
    borderColor: '#30B3AB',
    marginLeft: '2%',
    marginRight: '2%',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 6,
    },
    shadowOpacity: 0.8,
    shadowRadius: 6.84,
    elevation: 6,
    backgroundColor: "white"
  },
  AddIconActive: {
    height: PixelToDP(53),
    width: PixelToDP(53),
    marginTop: PixelToDP(9),
    borderRadius: PixelToDP(50),
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: PixelToDP(2),
    borderColor: 'white',
    marginLeft: '2%',
    marginRight: '2%',
    backgroundColor: '#3a9f9a',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.8,
    shadowRadius: 6.84,
    elevation: 3,
  },
  about: {
    fontSize: responsiveFontSize(2.6),
    color: 'white',
    lineHeight: PixelToDP(30),
    marginTop: PixelToDP(20),
    width: widthPercentageToDP(90),
    alignSelf: 'center',
    fontFamily: "SourceSansPro-Regular",
    textAlign: 'justify'
  },
  taskCompleted: {
    backgroundColor: '#2BCB4E',
    borderRadius: PixelToDP(30),
    width: responsiveFontSize(4),
    height: responsiveFontSize(4),
    justifyContent: 'center',
    alignSelf: 'center'
  },
  taskInCompleted: {
    borderRadius: PixelToDP(30),
    width: responsiveFontSize(4),
    height: responsiveFontSize(4),
    borderColor: 'black',
    borderWidth: PixelToDP(1),
    justifyContent: 'center',
    alignSelf: 'center'
  },
  dailyRemainderDay: {
    borderColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: PixelToDP(2),
    marginLeft: PixelToDP(2),
    width: responsiveFontSize(5),
    height: responsiveFontSize(5),
    borderRadius: responsiveFontSize(5)
  },
  dailyRemainderDayActive: {
    borderColor: 'white',
    alignItems: 'center',
    backgroundColor: 'white',
    justifyContent: 'center',
    borderWidth: PixelToDP(2),
    marginLeft: PixelToDP(2),
    width: responsiveFontSize(5),
    height: responsiveFontSize(5),
    borderRadius: responsiveFontSize(5)
  },
  dailyRemainderTextDay: {
    color: 'white',
    fontSize: responsiveFontSize(2),
    width: '100%',
    alignSelf: 'center',
    textAlign: 'center',
    fontFamily: "SourceSansPro-Regular"
  },
  dailyRemainderTextDayActive: {
    color: '#30B3AB',
    fontSize: responsiveFontSize(2),
    width: '100%',
    alignSelf: 'center',
    textAlign: 'center',
    fontFamily: "SourceSansPro-Regular"
  },
  customImage: {
    alignSelf: 'center',
    width: responsiveFontSize(4),
    height: responsiveFontSize(4)

  },
  nonCustomImage: {
    tintColor: '#22DCD3',
    alignSelf: 'center',
    width: responsiveFontSize(3.6),
    height: responsiveFontSize(3.6)
  },
  nonCustomTODoImage: {
    tintColor: '#ffffff',
    alignSelf: 'center',
    width: responsiveFontSize(2.5),
    height: responsiveFontSize(2.5)
  },
  nonCustomHomeImage: {
    tintColor: '#22DCD3',
    alignSelf: 'center',
    width: responsiveFontSize(4),
    height: responsiveFontSize(4)
  },
  customHomeImage: {
    borderRadius: PixelToDP(200),
    alignSelf: 'center',
    width: '100%',
    height: '100%',
    margin: PixelToDP(10)
  },
  shadow: {
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  cardStyleforCode: {
    width: PixelToDP(38),
    height: PixelToDP(38),
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: PixelToDP(20),
  },
  enterCodeKeyImage: {
    width: PixelToDP(38),
    height: PixelToDP(38),
    borderRadius: PixelToDP(25),
    borderColor: '#3FB5AB',
    borderWidth: PixelToDP(5)
  },
  enterCodeLogoBackground: {
    width: widthPercentageToDP(35),
    height: widthPercentageToDP(35),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#60C8C1',
    // elevation:PixelToDP(20),
    borderRadius: widthPercentageToDP(20),
    alignSelf: 'center',
  },
  loginTitle: {
    fontSize: responsiveFontSize(3.6),
    fontWeight: "bold",
    color: "white",
    marginTop: 30,
    marginBottom: 30,
    textAlign: "center"
  },
  loginText: {
    fontSize: responsiveFontSize(2.8),
    color: "white",
    marginTop: 10,
    marginBottom: 30,
    textAlign: "center"
  },
  registerTitle: {
    fontSize: responsiveFontSize(3.2),
    fontWeight: "bold",
    color: "white",
    marginTop: 0,
    marginBottom: 10,
    textAlign: "center"
  },
  registerText: {
    fontSize: responsiveFontSize(2.8),
    color: "white",
    marginTop: 0,
    marginBottom: 20,
    textAlign: "center"
  },
  loginSignup: {
    textAlign: "center",
    fontSize: responsiveFontSize(2.2),
    color: "white",
    marginTop: 15,
    paddingRight: 10,
    marginTop: 40
  },
  loginSignupText: {
    textAlign: "right",
    fontSize: responsiveFontSize(2.2),
    color: "white",
    fontWeight: "bold"
  },
  buttonsFooter: {
    width: widthPercentageToDP(40),
    borderRadius: widthPercentageToDP(40),
    backgroundColor: '#8fc6c2',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    width: '90%',
    marginTop: 50,
    margin: 'auto',
    alignSelf: 'center',
    shadowColor: '#3ca29b',
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowOpacity: 0.25,
    shadowRadius: 5.46,
    elevation: 4,
    position: 'absolute',
    height: heightPercentageToDP(9),
    top: heightPercentageToDP(77),

  },
  buttonsFooterText: {
    width: widthPercentageToDP(40),
    borderRadius: widthPercentageToDP(40),
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    width: '90%',
    margin: 'auto',
    alignSelf: 'center',
    position: 'absolute',
    top: heightPercentageToDP(95),

  },
  buttonsFooterTextTitle: {
    color: "white",
    fontSize: responsiveFontSize(2.6),
    textTransform: 'capitalize',
    fontFamily: 'SourceSansPro-Regular',
    letterSpacing: 0.7,
  },
  modalOuter: {
    borderWidth: 6,
    borderRadius: PixelToDP(20),
    borderColor: "#3a9f9a",
    width: widthPercentageToDP(85),
    alignSelf: 'center',
    paddingTop: PixelToDP(35),
    flexDirection: 'column',
    alignItems: "center",
    height: '90%',
    paddingBottom: 50,
    backgroundColor: "white",
  },
  modalBg: {
    backgroundColor: 'white',
    borderRadius: PixelToDP(0),
    height: heightPercentageToDP(80),
    width: widthPercentageToDP(85),
    alignSelf: 'center',
    alignItems: "center",
    borderWidth: 0,
    paddingTop: heightPercentageToDP(10),
    marginTop: 0,
    backgroundColor: "rgba(0,0,0,0.8)",
    height: heightPercentageToDP(100),
    width: "100%"
  },
  modalTitle: {
    fontSize: responsiveFontSize(2.5),
    fontWeight: 'bold',
    width: '80%',
    marginBottom: PixelToDP(20),
    textAlign: 'center',
    textAlignVertical: 'center',
    color: "#3a9f9a",
    alignSelf: "center"
  },
  modalTextArea: {
    borderWidth: 6,
    borderTopLeftRadius: PixelToDP(40),
    borderBottomRightRadius: PixelToDP(40),
    borderColor: "#3a9f9a",
    width: widthPercentageToDP(70),
    alignSelf: "center",
    backgroundColor: "#22DCD3",
    padding: 15,
    paddingTop: 35,
    paddingBottom: 35,
    justifyContent: "flex-start",
    shadowColor: '#121010',
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 0.8,
    shadowRadius: 3.84,
    elevation: 10,
  },
  modalText: {
    width: '90%',
    textAlign: "center",
    color: "white",
    alignSelf: "center",
    fontSize: responsiveFontSize(2),
    fontWeight: "bold"
  },
  IconBox: {
    borderWidth: 6,
    borderRadius: PixelToDP(20),
    borderColor: "#3a9f9a",
    width: widthPercentageToDP(85),
    alignSelf: 'center',
    paddingTop: PixelToDP(25),
    flexDirection: 'column',
    alignItems: 'center',
    paddingBottom: 50,
    backgroundColor: "white",
    shadowColor: '#121010',
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 0.8,
    shadowRadius: 3.84,
    elevation: 10,
  },
  TextInputCommon: {
    width: '90%',
    alignSelf: 'center',
    height: PixelToDP(41),
    borderRadius: PixelToDP(20),
    marginBottom: PixelToDP(20),
    borderColor: '#C4C4C4',
    borderWidth: PixelToDP(1),
    textAlign: 'center',
    padding: PixelToDP(10),
    fontFamily: "SourceSansPro-Regular",
    fontSize: responsiveFontSize(1.5),
    borderColor: '#58c3be',
    textAlign: 'center',
    borderWidth: PixelToDP(1),
    shadowColor: '#121010',
    backgroundColor: "#fff",
    fontSize: responsiveFontSize(2.5),
    borderWidth: 4,
    height: 55,
    shadowOffset: {
      width: 0,
      height: 6,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    color: '#4bc9c1',
    elevation: 6,
    paddingTop: 10,
    paddingBottom: 10
  },
  buttonLogin: {
    width: widthPercentageToDP(90),
    alignSelf: 'center',
    height: PixelToDP(40),
    alignItems: 'center',
    marginBottom: PixelToDP(10),
    marginTop: PixelToDP(30),
    borderColor: '#58c3be', textAlign: 'center', borderWidth: PixelToDP(1),
    shadowColor: '#121010',
    backgroundColor: "#fff",
    fontSize: responsiveFontSize(2.3),
    borderWidth: 4,
    height: 55,
    shadowOffset: {
      width: 0,
      height: 6,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    color: '#4bc9c1',
    elevation: 6,
    paddingTop: 10,
    paddingBottom: 10,
    borderRadius: 20,
  },
  journalsText: {
    fontSize: responsiveFontSize(2.5),
    fontWeight: 'bold',
    width: '100%',
    marginBottom: PixelToDP(5),
    textAlign: 'center',
    textAlignVertical: 'center',
    color: '#4bc9c1',
    alignSelf: "center"
  },
  journalsButtonText: {
    color: '#4bc9c1',
    width: '100%',
    textTransform: 'uppercase',
    fontSize: PixelToDP(18),
    textAlign: 'center',
    textAlignVertical: 'center',
    fontWeight: "bold"
  },
  errorMessage: {
    alignItems:"center",
    alignSelf:"center",
    fontSize:responsiveFontSize(2.0),
    color:"#ff0000",
    marginBottom:-10
  }
});
